JDP240701-15 ver.1
piotr-grosicki/project-jdp-2407-01 pull request #12
Opened 2024-07-10 07:13 UTC by kserafin92

2024-07-10 08:10 UTC, piotr-grosicki requested changes

2024-07-10 08:10 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +public class User {
chyba brakuje klucza :)

2024-07-11 18:05 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +public class User {
wciaz brakuje klucza :)

2024-07-11 18:05 UTC, piotr-grosicki submitted a review, later dismissed
wciaz brakuje klucza w encji

2024-07-11 18:32 UTC, likeahim requested changes

2024-07-11 18:32 UTC, likeahim commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +
może spróbuj dodać relację z Cart wg naszego schematu

2024-07-12 12:39 UTC, likeahim approved these changes

2024-07-12 13:38 UTC, merged