JDP240701-1
piotr-grosicki/project-jdp-2407-01 pull request #2
Opened 2024-07-05 16:14 UTC by likeahim

2024-07-06 07:25 UTC, piotr-grosicki requested changes

2024-07-06 07:25 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public ProductDto getProduct(Long productId) {
brakuje adnotacji do aprametru

2024-07-06 07:25 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public void createProduct(ProductDto productDto) {
brakuje adnotacji do aprametru

2024-07-06 07:25 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public ProductDto updateProduct(ProductDto productDto) {
brakuje adnotacji do aprametru

2024-07-06 07:25 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public void deleteProduct(Long productId) {
brakuje adnotacji do aprametru

2024-07-06 07:25 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/dto/ProductDto.java
> +public class ProductDto {
nie umowiliscie sie na uzywanie lomboka?

2024-07-06 13:24 UTC, likeahim commented on src/main/java/com/kodilla/ecommercee/domain/dto/ProductDto.java
> +public class ProductDto {
umówiliśmy się, ale nie było dependency lomboka i nie wiedziałem, czy możemy ją sami dodać. W pierwszym commicie dodałem, ale potem usunąłem. Zaraz będzie spowrotem.

2024-07-07 15:49 UTC, piotr-grosicki requested changes
konflikty: https://www.jetbrains.com/help/idea/resolve-conflicts.html

2024-07-07 19:23 UTC, merged